version: "3.9"

services:
  auth-service:
    build:
      context: ..
    ports:
      - "20005:20005"
    environment:
      CONFIG_PATH: "/app/config/config.yaml"
      PEM_FOLDER_PATH: "/app/config/pem"
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: Password
    command: mongod --auth --bind_ip_all
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:Password@mongo:27017
      ME_CONFIG_BASICAUTH: true
